### ISSUE TITLE
Quick Sort in C

### ISSUE THREAD

**Issue by 22tanyabansal** [AkshayNachappa/Hacktoberfest_2022#270]
I want to add program in Quick sort. Please assign this issue to me.

**Comment by AkshayNachappa** [comment]
Assigned

**Comment by 22tanyabansal** [comment]
Hey I added the repository of Quick sort. Please check it out.

**Comment by 22tanyabansal** [comment]
Hey @AkshayNachappa please merge this pull request in hacktoberfest 2022

**Comment by AkshayNachappa** [comment]
This project is excluded
